# Generated by Django 5.0.6 on 2024-05-18 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_chain_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='chain',
            name='chainID',
            field=models.IntegerField(default=12345),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='chainID',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, to='backend.chain'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='postID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
