# Generated by Django 5.0.6 on 2024-05-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_user_password_chain_chainid_post_chainid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_content',
            field=models.URLField(default=int),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='txt_content',
            field=models.TextField(default=int),
            preserve_default=False,
        ),
    ]
